<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoldERP.Application\GoldERP.Application.csproj" />
    <ProjectReference Include="..\GoldERP.Infrastructure\GoldERP.Infrastructure.csproj" />
    <ProjectReference Include="..\GoldERP.Shared\GoldERP.Shared.csproj" />
  </ItemGroup>

</Project>
